const projects = [
  {
    id: 1,
    title: "EduTrial the online learning Platform",
    image: "https://i.ibb.co.com/Cp18JmQM/edutrial.png",
    description:
      "EduTrial is a modern online learning platform designed to streamline class management and improve collaboration between students and instructors. Featuring secure authentication, role-based access control, and dynamic dashboards, it simplifies educational operations for all users. Focused on scalability, user experience, and efficiency, this platform is ideal for educational institutions and training centers.",
    features: [
      "Secure role-based access control",
      "Seamless payment integration with Stripe",
      "Comprehensive class management system",
      "Automated student enrollment process",
      "User-specific dashboards based on roles",
      "Effortless image upload & management",
      "Advanced search functionality with filters",
    ],

    technologies: [
      "react.js",
      "node.js",
      "mongodb",
      "express.js",
      "stripe",
      "firebase",
      "tailwind css",
      "jwt",
      "react hook form",
      "swiper.js",
      "react hot toast",
      "ant desing",
      "daisy UI",
      "tanstack query",
      "axios",
      "sweetAlert2",
      "react awesome reveal",
      "react stars",
    ],
    "main-technologies": [
      "react.js",
      "tailwind css",
      "node.js",
      "express.js",
      "mongodb",
    ],
    github: {
      client: "https://github.com/Hasinur3813/edutrial-client",
      server: "",
    },
    liveLink: "https://fir-learning-793eb.web.app",
    challenges: ["integration tanstack mutation", "dashboard layout desing"],
    improvements: [
      "Enhanced profile update system with real-time validation",
      "Integrated payment history tracking for user transparency",
      "Live customer support for instant issue resolution",
    ],
  },
  {
    id: 2,
    title: "EduLink the group studies platform",
    image: "https://i.ibb.co.com/wFb2cqGq/edulink.png",
    description:
      "EduLink is an online platform designed for group studies and collaborative learning. It allows users to create and manage assignments, submit completed tasks, and evaluate submissions seamlessly. The platform supports a user-friendly interface and secure access. EduLink aims to facilitate effective online group studies and assignment management, making it easy for educators and learners to collaborate efficiently.",
    features: [
      "create, view, and manage assignments",
      "submit and evaluate assignments with feedback and grading",
      "search funcionality",
      "dark mode functionality",
      "filter functionality",
    ],
    technologies: [
      "react.js",
      "node.js",
      "mongodb",
      "express.js",
      "firebase",
      "tailwind css",
      "jwt",
      "daisy UI",
      "axios",
      "sweetAlert2",
      "react awesome reveal",
    ],
    "main-technologies": [
      "react.js",
      "tailwind css",
      "node.js",
      "express.js",
      "mongodb",
    ],
    github: {
      client: "https://github.com/Hasinur3813/edulink-client",
      server: "",
    },
    liveLink: "https://edulink-5324d.web.app",
    challenges: [
      "authentication integration",
      "search functionality integration",
    ],
    improvements: [
      "profile view system",
      "profile updating system",
      "users chat services",
      "live customer support",
    ],
  },
  {
    id: 3,
    title: "NoteHub, a web based note taking app",
    image: "https://i.ibb.co.com/MDTcX90q/notehub.png ",
    description:
      "A web-based note-taking app where users can sign up, log in, create, read, update, and delete (CRUD) notes. The app also supports searching notes and categorizing them for easy access. Users can personalize their profile by updating their profile picture and changing their display name.",
    features: [
      "notes management",
      "category system",
      "search functionality",
      "profile management",
    ],
    technologies: [
      "react",
      "taiwind css",
      "material UI",
      "daisy UI",
      "firebase",
      "firebase-firestore",
    ],
    "main-technologies": [
      "react",
      "taiwind css",
      "material UI",
      "daisy UI",
      "firebase",
    ],
    github: {
      client: "https://github.com/Hasinur3813/notehub",
      server: "",
    },
    liveLink: "https://notehub.surge.sh",
    challenges: [
      "CRUD operation with firebase firestore",
      "sidebar integration",
      "image upload to the firebase storage",
    ],
    improvements: [
      "profile updating system",
      "implementation a professional modal",
      "integration text editor",
    ],
  },
  {
    id: 4,
    title: "Crowdcube - A crowd funding application",
    image: "https://i.ibb.co.com/NgQ7nGg3/crowdcube.png",
    description:
      "Crowdcube, a modern crowdfunding platform designed to connect individuals with meaningful campaigns. Whether you want to create your campaign or contribute to an existing one, Crowdcube makes it simple, transparent, and impactful.",
    features: [
      "User-Friendly Campaign Management",
      "Running Campaigns Highlighted",
      "All User Campaigns in One Place",
      "Secure and Transparent Donation System",
      "Deadline Awareness",
    ],
    technologies: [
      "react",
      "taiwind css",
      "React Icons",
      "React Tooltip",
      "firebase",
      "React Awesome Reveal",
      "Swiper.js",
      "Express.js",
      "MongoDB",
    ],
    "main-technologies": [
      "react",
      "taiwind css",
      "firebase",
      "express.js",
      "mongodb",
    ],
    github: {
      client: "https://github.com/Hasinur3813/crowd-funding-client",
      server: "",
    },
    liveLink: "https://crowd-funding-pltatform.web.app",
    challenges: [
      "CRUD operation with firebase firestore",
      "sidebar integration",
      "image upload to the firebase storage",
    ],
    improvements: [
      "profile updating system",
      "implementation a professional modal",
      "integration text editor",
    ],
  },
];

export default projects;
