const projects = [
  {
    id: 833,
    title: "E-Shop – Modern E-commerce Frontend",
    image: "https://i.ibb.co.com/rGYhyrCy/eshop-frontend.png",
    description:
      "E-Shop is a modern and responsive e-commerce frontend application designed to deliver a seamless shopping experience. It features dynamic product browsing, cart management, and smooth navigation powered by React and Vite. With optimized state management and clean UI design, the platform ensures high performance, scalability, and an engaging user experience across devices.",

    features: [
      "Dynamic product listing with category filtering",
      "Add to cart & cart management system",
      "Responsive and mobile-friendly UI",
      "Smooth product slider using Swiper.js",
      "User-friendly form handling with validation",
      "Toast notifications for real-time feedback",
      "Reusable and modular component structure",
    ],

    technologies: [
      "react.js",
      "vite",
      "redux toolkit",
      "react-redux",
      "react-router",
      "tailwind css",
      "axios",
      "react hook form",
      "react toastify",
      "swiper.js",
      "lucide icons",
      "react icons",
    ],

    "main-technologies": [
      "react.js",
      "redux toolkit",
      "tailwind css",
      "vite",
      "axios",
    ],

    github: {
      client: "https://github.com/Hasinur3813/eshop",
      server: "",
    },

    liveLink: "https://eshop-eight-coral.vercel.app",

    challenges: [
      "Managing global cart state efficiently using Redux Toolkit",
      "Optimizing performance for large product lists",
      "Implementing smooth UI/UX with Swiper and animations",
      "Handling form validation and error states properly",
    ],

    improvements: [
      "Product comparison features",
      "Improve SEO and performance optimization",
    ],
    createdAt: "2026-03-20",
    active: true,
  },
  {
    id: 22,
    title: "E-Shop Admin Dashboard",
    image: "https://i.ibb.co.com/cctPrjWB/eshop-admin.png",
    description:
      "E-Shop Admin Dashboard is a powerful and scalable admin panel designed for managing e-commerce operations efficiently. It provides real-time analytics, order tracking, product management, and user control in a clean and responsive interface. Built with modern frontend tools and optimized state management, it ensures high performance and seamless user experience for administrators.",

    features: [
      "Advanced admin dashboard with real-time analytics",
      "Comprehensive product & category management system",
      "Order tracking and status management",
      "User management with role-based access",
      "Sales reports with PDF export functionality",
      "Interactive charts and data visualization",
      "Responsive UI optimized for all devices",
    ],

    technologies: [
      "react.js",
      "vite",
      "redux toolkit",
      "react-redux",
      "react-router",
      "tailwind css",
      "axios",
      "react hook form",
      "react hot toast",
      "recharts",
      "html2canvas",
      "jspdf",
      "react icons",
    ],

    "main-technologies": [
      "react.js",
      "redux toolkit",
      "tailwind css",
      "vite",
      "axios",
    ],

    github: {
      client: "https://github.com/Hasinur3813/eshop-admin",
      server: "",
    },

    liveLink: "https://eshop-admin-gamma.vercel.app",

    challenges: [
      "Managing complex global state with Redux Toolkit",
      "Implementing dynamic charts with Recharts",
      "Generating downloadable reports using jsPDF and html2canvas",
      "Handling form validation efficiently with React Hook Form",
    ],

    improvements: [
      "Add real-time notifications for order updates",
      "Integrate role-based permission system for advanced admin control",
      "Implement dark mode for better user experience",
      "Add multi-language support for global usability",
    ],
    createdAt: "2026-03-18",
    active: true,
  },
  {
    id: 1,
    title: "EduTrial the online learning Platform",
    image: "https://i.ibb.co.com/Cp18JmQM/edutrial.png",
    description:
      "EduTrial is a modern online learning platform designed to streamline class management and improve collaboration between students and instructors. Featuring secure authentication, role-based access control, and dynamic dashboards, it simplifies educational operations for all users. Focused on scalability, user experience, and efficiency, this platform is ideal for educational institutions and training centers.",
    features: [
      "Secure role-based access control",
      "Seamless payment integration with Stripe",
      "Comprehensive class management system",
      "Automated student enrollment process",
      "User-specific dashboards based on roles",
      "Effortless image upload & management",
      "Advanced search functionality with filters",
    ],

    technologies: [
      "react.js",
      "node.js",
      "mongodb",
      "express.js",
      "stripe",
      "firebase",
      "tailwind css",
      "jwt",
      "react hook form",
      "swiper.js",
      "react hot toast",
      "ant desing",
      "daisy UI",
      "tanstack query",
      "axios",
      "sweetAlert2",
      "react awesome reveal",
      "react stars",
    ],
    "main-technologies": [
      "react.js",
      "tailwind css",
      "node.js",
      "express.js",
      "mongodb",
    ],
    github: {
      client: "https://github.com/Hasinur3813/edutrial-client",
      server: "",
    },
    liveLink: "https://fir-learning-793eb.web.app",
    challenges: ["Integration tanstack mutation", "Dashboard layout desing"],
    improvements: [
      "Enhance profile update system with real-time validation",
      "Integrate payment history tracking for user transparency",
      "Live customer support for instant issue resolution",
    ],
    createdAt: "2025-03-20",
    active: true,
  },
  {
    id: 2,
    title: "EduLink the group studies platform",
    image: "https://i.ibb.co.com/wFb2cqGq/edulink.png",
    description:
      "EduLink is an online platform designed for group studies and collaborative learning. It allows users to create and manage assignments, submit completed tasks, and evaluate submissions seamlessly. The platform supports a user-friendly interface and secure access. EduLink aims to facilitate effective online group studies and assignment management, making it easy for educators and learners to collaborate efficiently.",
    features: [
      "create, view, and manage assignments",
      "submit and evaluate assignments with feedback and grading",
      "search funcionality",
      "dark mode functionality",
      "filter functionality",
    ],
    technologies: [
      "react.js",
      "node.js",
      "mongodb",
      "express.js",
      "firebase",
      "tailwind css",
      "jwt",
      "daisy UI",
      "axios",
      "sweetAlert2",
      "react awesome reveal",
    ],
    "main-technologies": [
      "react.js",
      "tailwind css",
      "node.js",
      "express.js",
      "mongodb",
    ],
    github: {
      client: "https://github.com/Hasinur3813/edulink-client",
      server: "",
    },
    liveLink: "https://edulink-5324d.web.app",
    challenges: [
      "authentication integration",
      "search functionality integration",
    ],
    improvements: [
      "profile view system",
      "profile updating system",
      "users chat services",
      "live customer support",
    ],
    createdAt: "2025-06-20",
    active: true,
  },
  {
    id: 3,
    title: "NoteHub, a web based note taking app",
    image: "https://i.ibb.co.com/MDTcX90q/notehub.png ",
    description:
      "A web-based note-taking app where users can sign up, log in, create, read, update, and delete (CRUD) notes. The app also supports searching notes and categorizing them for easy access. Users can personalize their profile by updating their profile picture and changing their display name.",
    features: [
      "notes management",
      "category system",
      "search functionality",
      "profile management",
    ],
    technologies: [
      "react",
      "taiwind css",
      "material UI",
      "daisy UI",
      "firebase",
      "firebase-firestore",
    ],
    "main-technologies": [
      "react",
      "taiwind css",
      "material UI",
      "daisy UI",
      "firebase",
    ],
    github: {
      client: "https://github.com/Hasinur3813/notehub",
      server: "",
    },
    liveLink: "https://notehub.surge.sh",
    challenges: [
      "CRUD operation with firebase firestore",
      "sidebar integration",
      "image upload to the firebase storage",
    ],
    improvements: [
      "profile updating system",
      "implementation a professional modal",
      "integration text editor",
    ],
    createdAt: "2025-04-10",
    active: true,
  },
  {
    id: 4,
    title: "Crowdcube - A crowd funding application",
    image: "https://i.ibb.co.com/NgQ7nGg3/crowdcube.png",
    description:
      "Crowdcube, a modern crowdfunding platform designed to connect individuals with meaningful campaigns. Whether you want to create your campaign or contribute to an existing one, Crowdcube makes it simple, transparent, and impactful.",
    features: [
      "User-Friendly Campaign Management",
      "Running Campaigns Highlighted",
      "All User Campaigns in One Place",
      "Secure and Transparent Donation System",
      "Deadline Awareness",
    ],
    technologies: [
      "react",
      "taiwind css",
      "React Icons",
      "React Tooltip",
      "firebase",
      "React Awesome Reveal",
      "Swiper.js",
      "Express.js",
      "MongoDB",
    ],
    "main-technologies": [
      "react",
      "taiwind css",
      "firebase",
      "express.js",
      "mongodb",
    ],
    github: {
      client: "https://github.com/Hasinur3813/crowd-funding-client",
      server: "",
    },
    liveLink: "https://crowd-funding-pltatform.web.app",
    challenges: [],
    improvements: [
      "Real time donation system",
      "Integration dashboard layout",
      "Role base access control.",
    ],
    createdAt: "2026-07-20",
    active: true,
  },
  {
    id: 5,
    title: "Winte Donation - A winter clothing donation app",
    image: "https://i.ibb.co.com/vCXL2w6s/winter-clothing-web-app.png",
    description:
      "This project was created to facilitate winter clothing donations and streamline the process of connecting donors and recipients. It allows users to donate, volunteer, and participate in campaigns to make a difference in the lives of underprivileged individuals across Bangladesh.",
    features: [
      "Secure user authentication and authorization",
      "User-friendly donation process",
      "friendly campaign management",
      "user dashboard",
    ],
    technologies: [
      "react",
      "taiwind css",
      "react icons",
      "firebase",
      "react awesome reveal",
      "swiper.js",
      "react-toastify",
    ],
    "main-technologies": ["react", "taiwind css", "firebase"],
    github: {
      client: "https://github.com/Hasinur3813/winter-clothing",
      server: "",
    },
    liveLink: "https://winter-clothing.web.app",
    challenges: [],
    improvements: [
      "Connect with backend",
      "Real time donation system",
      "Integration dashboard layout",
      "Role base access control.",
      "Integration of payment gateway",
    ],
    createdAt: "2025-04-10",
    active: true,
  },
];

export default projects;
